manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: urob
      url-base: https://github.com/urob
    - name: dhruvinsh
      url-base: https://github.com/dhruvinsh

  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
      revision: v0.3

    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: v0.3
    - name: zmk-tri-state
      remote: dhruvinsh

    - name: zmk-helpers
      remote: urob
      path: modules/zmk/helpers
    - name: zmk-auto-layer
      remote: urob
      path: modules/zmk/auto-layer
    - name: zmk-adaptive-key
      remote: urob
      path: modules/zmk/adaptive-key

  self:
    path: config
